# Generated by Django 4.0.8 on 2022-10-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OLXstats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('stat_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city_id', models.IntegerField()),
                ('date', models.DateField()),
                ('avg_m2_price_primary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_m2_price_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_m2_price_all', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_unit_price_primary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_unit_price_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('avg_unit_price_all', models.DecimalField(decimal_places=2, max_digits=15)),
                ('count_primary', models.IntegerField()),
                ('count_after', models.IntegerField()),
                ('count_all', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='AptDetails',
        ),
        migrations.DeleteModel(
            name='AptPrices',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='Districts',
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
    ]
